# Generated by Django 5.2.4 on 2025-07-29 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('status', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'applications',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Candidate',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=100)),
                ('domain', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'candidates',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='InteractionLog',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('interaction_type', models.CharField(max_length=20)),
                ('timestamp', models.DateTimeField()),
            ],
            options={
                'db_table': 'interaction_log',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('company', models.CharField(max_length=100, null=True)),
                ('location', models.CharField(max_length=100)),
                ('domain', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'jobs',
                'managed': False,
            },
        ),
    ]
